### ISSUE TITLE
text color in story can't change

### ISSUE THREAD

**Issue by faga295** [element-plus/element-plus-interactive-docs#118]
https://element-plus-interactive-docs.netlify.app/story/src-components-data-pagination-story-vue?variantId=src-components-data-pagination-story-vue-0. 
Text in this story can't change with background color, currently, we can use `--histoire-contrast-color` css variable to implement it.
reference link:
https://histoire.dev/reference/config.html#backgroundpresets

**Comment by FliPPeDround** [comment]
I'm sorry,  I can't understanding about `can't change with background color`
![image](https://user-images.githubusercontent.com/70848683/219527906-675bd1ab-ea6b-46ff-9e82-46f3df61e10d.png)
That doesn't seem to be a problem, can you elaborate on that?

**Comment by faga295** [comment]
histoire has its own background color
<img width="235" alt="image" src="https://user-images.githubusercontent.com/87003751/219528240-2e25a10a-38ac-4efc-9e70-c738e3799fc3.png">
try to change with it.

**Comment by faga295** [comment]
<img width="563" alt="image" src="https://user-images.githubusercontent.com/87003751/219529370-c6686ee2-3d80-4b0c-8418-48b392db94db.png">

**Comment by FliPPeDround** [comment]
If we modify the color of the component by `--histoire-contrast-colo`, 
this introduces a new feature which is not a capability of element-plus itself and can create a misunderstanding to the user that the element-plus component will adapt itself to change whenever the background color is changed in use. 
Do you have any good solution for this?

**Comment by faga295** [comment]
it should still use `--histoire-constrast-color--`,in my opinion,  every `Variant` has its own background, it's independent of the overall background.On the flip side, use `--histoire-constrast-color--` tutorial can always read text clearly

**Comment by FliPPeDround** [comment]
Maybe you can make it happen, it's more convincing ;)
