### ISSUE TITLE
[RFC] 建议自动化初始化组件流程

### ISSUE THREAD

**Issue by c0dedance** [element-plus/element-plus-interactive-docs#35]
## 痛点分析

1. 组件规范靠大家自觉遵守

   默认是`src/components/`下组件类型文件夹进行归类，组件文档小驼峰，以`.story.vue`结尾

2. 手动归类建文件夹可能会混乱

3. 手动建文件不够优雅

### 命令生成

文档复制组件名粘贴至命令行
![image](https://user-images.githubusercontent.com/38075730/195988814-5575bcea-32a1-4c93-822e-3d64dd7d36e9.png)

~~~shell
# 创建单个组件文档
pnpm run create Button
# 创建多个组件文档
pnpm run create DatePicker InputNumber

datePicker.story.vue创建成功！
path:D:/Desktop/code/fork/element-plus-docs-histoire/src/components/Form/datePicker.story.vue
inputNumber.story.vue创建成功！
path:D:/Desktop/code/fork/element-plus-docs-histoire/src/components/Form/inputNumber.story.vue
~~~

### 命令行交互生成

![image](https://user-images.githubusercontent.com/38075730/195988562-36ba0d6b-8f52-40be-84ec-0e63d7fe2ad2.png)
![image](https://user-images.githubusercontent.com/38075730/195988606-cca75906-dba6-441e-b521-8125bda243f9.png)

~~~shell
button.story.vue已存在！
color.story.vue创建成功！
path:D:/Desktop/code/fork/element-plus-docs-histoire/src/components/Basic/color.story.vue
~~~

**Comment by FliPPeDround** [comment]
太棒了，如果你完成的话，这将是一个非常有趣PR！！！
一个小建议：可以在选择创建组件前，扫一遍选中文件夹，如果已经存在的组件，将不在可选范围内。
